name: mujersegura
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.3
  provider:
  flutter_spinkit:
  firebase_analytics: ^5.0.10
  firebase_auth: ^0.16.1
  firebase_storage: ^3.0.3 
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.2+1
  google_sign_in: ^4.5.1
  shared_preferences: ^0.5.6
  intl:
  font_awesome_flutter:
  pin_code_fields:

  connectivity: ^0.4.9
  carousel_slider: ^2.1.0
  url_launcher: ^5.4.5
  expansion_tile_card: ^1.0.3
  equatable: 
  meta: 
  http:
  html:
  rxdart:


  page_view_indicators: ^1.3.1
  progress_dialog: ^1.2.2
  image_picker: ^0.5.0
  cached_network_image: ^2.1.0+1
  geolocator: ^5.1.4+2



  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

module:
  androidX: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/onboarding/